### ISSUE TITLE
Help launcher error

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#11]
"At this time only 2 accounts can be created on this computer."
I havent even created one help!

**Comment by InvisbleMario** [comment]
Other people in your house could've created two.

**Comment by mgracer48** [comment]
Nope they dont know about this game

**Comment by InvisbleMario** [comment]
Try resetting your router.

**Comment by xMakerx** [comment]
Hey there, mgracer48!

The login server probably crashed. Please give me some time to correct the
issue and I'll contact you when everything is running okay.

Best regards,
DecodedLogic (Deputy B.D.)

**Comment by mgracer48** [comment]
Thanks xmaker

**Comment by InvisbleMario** [comment]
Sorry Maker! Thought it was an issue with the router.

**Comment by xMakerx** [comment]
You're welcome, mgracer48. I just put the server up. Please hurry up and make your account now because your account will put us at the account limit. HURRY!

**Comment by mgracer48** [comment]
same error weird

**Comment by xMakerx** [comment]
Please email me your IP address so I can look into the problem. Email: decodedlogic@coginvasion.com

**Comment by mgracer48** [comment]
thank you for the help

**Comment by xMakerx** [comment]
You're very welcome! I hope you have fun in the game once you get to play.

**Comment by mgracer48** [comment]
I will and I hope some day i can be a moderator for you game :)
