### ISSUE TITLE
after selecting toon and loading i am stuck on gray screen

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#13]

**Comment by mgracer48** [comment]
https://www.dropbox.com/s/wsbnf19o2lt5nez/screenshot-Fri-Nov-06-18-27-31-2015-9742.jpg?dl=0

**Comment by mgracer48** [comment]
Also my fan is like really loud when this happens. Memory leak?

**Comment by mgracer48** [comment]
p.s im using mac and wine

**Comment by InvisbleMario** [comment]
CIO doesn't support wine. It's third party software used to circumvent the need for actual support from them. When they do release support problems like this shouldn't happen.

**Comment by mgracer48** [comment]
Ill close
