### ISSUE TITLE
you guys should change to launchpad

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#15]
to track issues

**Comment by InvisbleMario** [comment]
Stop spamming us.

**Comment by mgracer48** [comment]
@InvisbleMario Sorry im just suggesting things for you don't need to be rude.

**Comment by InvisbleMario** [comment]
An issue tracker is not really meant for suggesting things.

**Comment by InvisbleMario** [comment]
We're already using Github. Suggestions should be for the game only.
