### ISSUE TITLE
after round 2 of eagle mini  game you get black screen and cant see anything

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#24]

**Comment by mgracer48** [comment]
only happens sometimes

**Comment by InvisbleMario** [comment]
Provide a log. Or steps to reproduce. xMakerx and ducky can't do much with "only happens sometimes"

**Comment by mgracer48** [comment]
I dont know how its reproduced exactly

**Comment by InvisbleMario** [comment]
Is it ok if I can close this for now until you find how to reproduce?

**Comment by mgracer48** [comment]
No because it happened randomly it was a black screen

**Comment by InvisbleMario** [comment]
Could be a district reset/crash.

**Comment by mgracer48** [comment]
Still a bug that needs fixing if a district crashes :)

**Comment by mgracer48** [comment]
actually i had the unlimited cupcakes when i did this minigame so maybe your right
