### ISSUE TITLE
cupcake unlimited gags

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#25]
Ok i love this glitch because it saves me jellybeans but its also a glitch so i have to report it

**Comment by InvisbleMario** [comment]
This only happens when the district crashes.

**Comment by mgracer48** [comment]
Invalid what the heck? So you guys want to keep the glitches? ok

**Comment by InvisbleMario** [comment]
I said. This only happens when the district crashes.

**Comment by mgracer48** [comment]
Yea and? that is still a glitch
