### ISSUE TITLE
game wont even start, error

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#31]
Unhandled exception: page fault on read access to 0x011e6536 in 32-bit code (0x7b830b51).
Register dump:
 CS:001b SS:0023 DS:0023 ES:0023 FS:1007 GS:000f
 EIP:7b830b51 ESP:00f5fdb0 EBP:00f5fde4 EFLAGS:00010202(  R- --  I   - - - )
 EAX:011341c6 EBX:00000000 ECX:00000064 EDX:0000005c
 ESI:00f5fdf0 EDI:01144137
Stack dump:
0x00f5fdb0:  ffff0000 00f5fe18 ffff0000 7bc6849f
0x00f5fdc0:  f7056541 00002446 00000064 00000000
0x00f5fdd0:  00f5fe18 00000000 00f5fde8 00f5fdf0
0x00f5fde0:  01144137 00f5fe2c 0040139b 00000000
0x00f5fdf0:  00000001 00000000 00000000 36483f85
0x00f5fe00:  01144137 00f5fdf0 00f5fdf4 00f5fdf0
0200: sel=1007 base=7ffc0000 limit=00000fff 32-bit rw-
Backtrace:
=>0 0x7b830b51 in kernel32 (+0x20b51) (0x00f5fde4)
  1 0x0040139b in coginvasion (+0x139a) (0x00f5fe2c)
  2 0x00a69000 in coginvasion (+0x668fff) (0x00f5fdf8)
0x7b830b51: testb	$0x1,0xb2370(%eax)
Modules:
Module	Address			Debug info	Name (20 modules)
PE	  400000-  b56000	Export          coginvasion
PE	1e000000-1e261000	Deferred        python27
PE	40470000-4049e000	Deferred        user32
PE	405b0000-405b4000	Deferred        gdi32
PE	407a0000-407a4000	Deferred        advapi32
PE	40810000-40814000	Deferred        version
PE	40820000-40827000	Deferred        oleaut32
PE	40940000-40948000	Deferred        ole32
PE	40a70000-40a74000	Deferred        rpcrt4
PE	40b00000-40c0e000	Deferred        shell32
PE	40ce0000-40ce4000	Deferred        shlwapi
PE	40d60000-40d80000	Deferred        comctl32
PE	40e50000-40e54000	Deferred        msvcr90
PE	40e80000-40e84000	Deferred        msvcrt
PE	40fa0000-40fa3000	Deferred        winemac
PE	42e80000-42e84000	Deferred        uxtheme
PE	43020000-43024000	Deferred        shfolder
PE	78aa0000-78b5f000	Deferred        msvcr100
PE	7b810000-7b866000	Export          kernel32
PE	7bc10000-7bc14000	Deferred        ntdll
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	0000001e    0
	0000001d    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001a    0
	00000019    0
	00000017    0
	00000013    0
0000001b plugplay.exe
	00000020    0
	0000001f    0
	0000001c    0
00000021 explorer.exe
	00000023    0
	00000022    0
0000002c (D) C:\Program Files\Cog Invasion Online\coginvasion.exe
	00000031    0
	00000030    0
	0000002d    0 <==
0000002e wineconsole.exe
	0000002f    0
System information:
    Wine build: wine-1.6.2
    Platform: i386
    Host system: Darwin
    Host version: 15.0.0
terminal says : 
wine: Unhandled page fault on read access to 0x011e6536 at address 0x7b830b51 (thread 002d), starting debugger...
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}

**Comment by InvisbleMario** [comment]
CIO doesn't support wine.

**Comment by mgracer48** [comment]
Still open this back up it was working before
